/********************************************************************************
** Form generated from reading UI file 'viewcalender.ui'
**
** Created: Sun Apr 15 15:37:46 2012
**      by: Qt User Interface Compiler version 4.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VIEWCALENDER_H
#define UI_VIEWCALENDER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QTextEdit>

QT_BEGIN_NAMESPACE

class Ui_ViewCalender
{
public:
    QGroupBox *groupBox;
    QPushButton *pushButton_2;
    QPushButton *pushButton;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLineEdit *lineEdit;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QGroupBox *groupBox_3;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QPushButton *pushButton_8;
    QPushButton *pushButton_13;
    QGroupBox *groupBox_2;
    QTextEdit *textEdit;
    QLineEdit *lineEdit_6;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_14;

    void setupUi(QDialog *ViewCalender)
    {
        if (ViewCalender->objectName().isEmpty())
            ViewCalender->setObjectName(QString::fromUtf8("ViewCalender"));
        ViewCalender->resize(793, 545);
        groupBox = new QGroupBox(ViewCalender);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(30, 10, 311, 511));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        groupBox->setFont(font);
        pushButton_2 = new QPushButton(groupBox);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(70, 70, 31, 23));
        QPalette palette;
        QBrush brush(QColor(0, 116, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_2->setPalette(palette);
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_2->setFont(font1);
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(30, 70, 31, 23));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton->setPalette(palette1);
        pushButton->setFont(font1);
        pushButton_3 = new QPushButton(groupBox);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(110, 70, 31, 23));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_3->setPalette(palette2);
        pushButton_3->setFont(font1);
        pushButton_4 = new QPushButton(groupBox);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(150, 70, 31, 23));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_4->setPalette(palette3);
        pushButton_4->setFont(font1);
        pushButton_5 = new QPushButton(groupBox);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(190, 70, 31, 23));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_5->setPalette(palette4);
        pushButton_5->setFont(font1);
        pushButton_6 = new QPushButton(groupBox);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(230, 70, 31, 23));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_6->setPalette(palette5);
        pushButton_6->setFont(font1);
        pushButton_7 = new QPushButton(groupBox);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(270, 70, 31, 23));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_7->setPalette(palette6);
        pushButton_7->setFont(font1);
        lineEdit = new QLineEdit(groupBox);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(20, 40, 281, 20));
        QPalette palette7;
        QBrush brush2(QColor(255, 85, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit->setPalette(palette7);
        QFont font2;
        font2.setPointSize(8);
        lineEdit->setFont(font2);
        pushButton_23 = new QPushButton(groupBox);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(30, 110, 31, 23));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_23->setPalette(palette8);
        pushButton_24 = new QPushButton(groupBox);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(70, 110, 31, 23));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_24->setPalette(palette9);
        pushButton_25 = new QPushButton(groupBox);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(110, 110, 31, 23));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_25->setPalette(palette10);
        pushButton_26 = new QPushButton(groupBox);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(150, 110, 31, 23));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_26->setPalette(palette11);
        pushButton_27 = new QPushButton(groupBox);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(190, 110, 31, 23));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_27->setPalette(palette12);
        pushButton_28 = new QPushButton(groupBox);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(230, 110, 31, 23));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_28->setPalette(palette13);
        pushButton_29 = new QPushButton(groupBox);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(270, 110, 31, 23));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_29->setPalette(palette14);
        pushButton_30 = new QPushButton(groupBox);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(30, 150, 31, 23));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_30->setPalette(palette15);
        pushButton_31 = new QPushButton(groupBox);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(70, 150, 31, 23));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_31->setPalette(palette16);
        pushButton_32 = new QPushButton(groupBox);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(110, 150, 31, 23));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_32->setPalette(palette17);
        pushButton_33 = new QPushButton(groupBox);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(150, 150, 31, 23));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_33->setPalette(palette18);
        pushButton_34 = new QPushButton(groupBox);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(190, 150, 31, 23));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_34->setPalette(palette19);
        pushButton_35 = new QPushButton(groupBox);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(230, 150, 31, 23));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_35->setPalette(palette20);
        pushButton_36 = new QPushButton(groupBox);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(270, 150, 31, 23));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_36->setPalette(palette21);
        pushButton_37 = new QPushButton(groupBox);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(30, 190, 31, 23));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_37->setPalette(palette22);
        pushButton_38 = new QPushButton(groupBox);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(70, 190, 31, 23));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_38->setPalette(palette23);
        pushButton_39 = new QPushButton(groupBox);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(110, 190, 31, 23));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_39->setPalette(palette24);
        pushButton_40 = new QPushButton(groupBox);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(150, 190, 31, 23));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_40->setPalette(palette25);
        pushButton_41 = new QPushButton(groupBox);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(190, 190, 31, 23));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_41->setPalette(palette26);
        pushButton_42 = new QPushButton(groupBox);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(230, 190, 31, 23));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_42->setPalette(palette27);
        pushButton_43 = new QPushButton(groupBox);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(270, 190, 31, 23));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_43->setPalette(palette28);
        pushButton_44 = new QPushButton(groupBox);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(30, 230, 31, 23));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_44->setPalette(palette29);
        pushButton_45 = new QPushButton(groupBox);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(70, 230, 31, 23));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_45->setPalette(palette30);
        pushButton_46 = new QPushButton(groupBox);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(110, 230, 31, 23));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_46->setPalette(palette31);
        lineEdit_4 = new QLineEdit(groupBox);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(100, 330, 101, 20));
        lineEdit_5 = new QLineEdit(groupBox);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(100, 360, 101, 20));
        pushButton_47 = new QPushButton(groupBox);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(210, 330, 75, 23));
        QPalette palette32;
        QBrush brush3(QColor(76, 76, 229, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette32.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette32.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette32.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_47->setPalette(palette32);
        QFont font3;
        font3.setPointSize(7);
        pushButton_47->setFont(font3);
        pushButton_48 = new QPushButton(groupBox);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(10, 330, 81, 23));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette33.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette33.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_48->setPalette(palette33);
        pushButton_48->setFont(font3);
        pushButton_49 = new QPushButton(groupBox);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(10, 360, 81, 23));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette34.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette34.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_49->setPalette(palette34);
        pushButton_49->setFont(font3);
        pushButton_50 = new QPushButton(groupBox);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(210, 360, 75, 23));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette35.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette35.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_50->setPalette(palette35);
        pushButton_50->setFont(font3);
        groupBox_3 = new QGroupBox(groupBox);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 400, 281, 101));
        label = new QLabel(groupBox_3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 46, 31));
        QFont font4;
        font4.setPointSize(17);
        label->setFont(font4);
        label_2 = new QLabel(groupBox_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 60, 46, 13));
        label_2->setFont(font2);
        lineEdit_2 = new QLineEdit(groupBox_3);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(60, 30, 91, 21));
        lineEdit_3 = new QLineEdit(groupBox_3);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(60, 60, 91, 20));
        pushButton_8 = new QPushButton(groupBox_3);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(180, 70, 81, 23));
        QPalette palette36;
        QBrush brush4(QColor(0, 85, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette36.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette36.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette36.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_8->setPalette(palette36);
        pushButton_13 = new QPushButton(groupBox);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(10, 280, 291, 23));
        QPalette palette37;
        QBrush brush5(QColor(170, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette37.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette37.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette37.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_13->setPalette(palette37);
        QFont font5;
        font5.setPointSize(9);
        pushButton_13->setFont(font5);
        groupBox_2 = new QGroupBox(ViewCalender);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(419, 10, 371, 481));
        QFont font6;
        font6.setPointSize(13);
        font6.setBold(true);
        font6.setWeight(75);
        groupBox_2->setFont(font6);
        textEdit = new QTextEdit(groupBox_2);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(10, 50, 341, 421));
        QFont font7;
        font7.setPointSize(11);
        textEdit->setFont(font7);
        lineEdit_6 = new QLineEdit(groupBox_2);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(20, 30, 321, 16));
        pushButton_9 = new QPushButton(ViewCalender);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(350, 80, 51, 21));
        QPalette palette38;
        QBrush brush6(QColor(132, 132, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette38.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_9->setPalette(palette38);
        QFont font8;
        font8.setPointSize(10);
        font8.setBold(true);
        font8.setWeight(75);
        pushButton_9->setFont(font8);
        pushButton_10 = new QPushButton(ViewCalender);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(350, 280, 51, 21));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette39.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette39.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_10->setPalette(palette39);
        pushButton_10->setFont(font8);
        pushButton_11 = new QPushButton(ViewCalender);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(350, 390, 51, 21));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette40.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette40.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_11->setPalette(palette40);
        pushButton_11->setFont(font8);
        pushButton_12 = new QPushButton(ViewCalender);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(350, 180, 51, 21));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette41.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette41.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_12->setPalette(palette41);
        pushButton_12->setFont(font8);
        pushButton_14 = new QPushButton(ViewCalender);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(620, 510, 75, 23));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette42.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette42.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_14->setPalette(palette42);
        pushButton_14->setFont(font1);

        retranslateUi(ViewCalender);

        QMetaObject::connectSlotsByName(ViewCalender);
    } // setupUi

    void retranslateUi(QDialog *ViewCalender)
    {
        ViewCalender->setWindowTitle(QApplication::translate("ViewCalender", "Dialog", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("ViewCalender", "Calender", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("ViewCalender", "2", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("ViewCalender", "1", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("ViewCalender", "3", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("ViewCalender", "4", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("ViewCalender", "5", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("ViewCalender", "6", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("ViewCalender", "7", 0, QApplication::UnicodeUTF8));
        pushButton_23->setText(QApplication::translate("ViewCalender", "8", 0, QApplication::UnicodeUTF8));
        pushButton_24->setText(QApplication::translate("ViewCalender", "9", 0, QApplication::UnicodeUTF8));
        pushButton_25->setText(QApplication::translate("ViewCalender", "10", 0, QApplication::UnicodeUTF8));
        pushButton_26->setText(QApplication::translate("ViewCalender", "11", 0, QApplication::UnicodeUTF8));
        pushButton_27->setText(QApplication::translate("ViewCalender", "12", 0, QApplication::UnicodeUTF8));
        pushButton_28->setText(QApplication::translate("ViewCalender", "13", 0, QApplication::UnicodeUTF8));
        pushButton_29->setText(QApplication::translate("ViewCalender", "14", 0, QApplication::UnicodeUTF8));
        pushButton_30->setText(QApplication::translate("ViewCalender", "15", 0, QApplication::UnicodeUTF8));
        pushButton_31->setText(QApplication::translate("ViewCalender", "16", 0, QApplication::UnicodeUTF8));
        pushButton_32->setText(QApplication::translate("ViewCalender", "17", 0, QApplication::UnicodeUTF8));
        pushButton_33->setText(QApplication::translate("ViewCalender", "18", 0, QApplication::UnicodeUTF8));
        pushButton_34->setText(QApplication::translate("ViewCalender", "19", 0, QApplication::UnicodeUTF8));
        pushButton_35->setText(QApplication::translate("ViewCalender", "20", 0, QApplication::UnicodeUTF8));
        pushButton_36->setText(QApplication::translate("ViewCalender", "21", 0, QApplication::UnicodeUTF8));
        pushButton_37->setText(QApplication::translate("ViewCalender", "22", 0, QApplication::UnicodeUTF8));
        pushButton_38->setText(QApplication::translate("ViewCalender", "23", 0, QApplication::UnicodeUTF8));
        pushButton_39->setText(QApplication::translate("ViewCalender", "24", 0, QApplication::UnicodeUTF8));
        pushButton_40->setText(QApplication::translate("ViewCalender", "25", 0, QApplication::UnicodeUTF8));
        pushButton_41->setText(QApplication::translate("ViewCalender", "26", 0, QApplication::UnicodeUTF8));
        pushButton_42->setText(QApplication::translate("ViewCalender", "27", 0, QApplication::UnicodeUTF8));
        pushButton_43->setText(QApplication::translate("ViewCalender", "28", 0, QApplication::UnicodeUTF8));
        pushButton_44->setText(QApplication::translate("ViewCalender", "29", 0, QApplication::UnicodeUTF8));
        pushButton_45->setText(QApplication::translate("ViewCalender", "30", 0, QApplication::UnicodeUTF8));
        pushButton_46->setText(QApplication::translate("ViewCalender", "31", 0, QApplication::UnicodeUTF8));
        pushButton_47->setText(QApplication::translate("ViewCalender", "Next Year >>", 0, QApplication::UnicodeUTF8));
        pushButton_48->setText(QApplication::translate("ViewCalender", "<< Prev. Year", 0, QApplication::UnicodeUTF8));
        pushButton_49->setText(QApplication::translate("ViewCalender", "<<prev. mon", 0, QApplication::UnicodeUTF8));
        pushButton_50->setText(QApplication::translate("ViewCalender", "next mon>>", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("ViewCalender", "Jump to a month", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("ViewCalender", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:17pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#55aa00;\">Year : </span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("ViewCalender", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#00aa7f;\">Month : </span></p></body></html>", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("ViewCalender", "Jump", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("ViewCalender", "Highlight the days that contains my writing", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("ViewCalender", "what's on your mind ?", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("ViewCalender", "Add", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("ViewCalender", "Edit", 0, QApplication::UnicodeUTF8));
        pushButton_11->setText(QApplication::translate("ViewCalender", "Delete", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("ViewCalender", "View", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("ViewCalender", "back", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ViewCalender: public Ui_ViewCalender {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VIEWCALENDER_H
